# Generated by Django 4.0 on 2022-03-17 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('departMent', models.CharField(choices=[('CSE', 'CSE'), ('ENGLISH', 'ENGLISH'), ('BBA', 'BBA'), ('BANGLA', 'BANGLA'), ('ISLAMIC STUDIES', 'ISLAMIC STUDIES'), ('EEE', 'EEE')], default='CSE', max_length=200)),
                ('ssc_gpa', models.FloatField()),
                ('hsc_gpa', models.FloatField()),
                ('referece_number', models.CharField(default='8341', max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Done',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myversity.registration')),
            ],
        ),
    ]
