# Generated by Django 3.2.6 on 2022-04-27 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('departMent', models.CharField(choices=[('CSE', 'CSE'), ('ENGLISH', 'ENGLISH'), ('BBA', 'BBA'), ('BANGLA', 'BANGLA'), ('ISLAMIC STUDIES', 'ISLAMIC STUDIES'), ('EEE', 'EEE')], default='CSE', max_length=200)),
                ('ssc_gpa', models.FloatField()),
                ('hsc_gpa', models.FloatField()),
                ('referece_number', models.CharField(default='6513', max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_All_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departMent', models.CharField(choices=[('CSE', 'CSE'), ('ENGLISH', 'ENGLISH'), ('BBA', 'BBA'), ('BANGLA', 'BANGLA'), ('ISLAMIC STUDIES', 'ISLAMIC STUDIES'), ('EEE', 'EEE')], default='CSE', max_length=200)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('maritial_status', models.CharField(choices=[('Married', 'Married'), ('UnMarried', 'UnMarried')], default='Unmarried', max_length=200)),
                ('blood_Group', models.CharField(max_length=10)),
                ('national_id', models.IntegerField()),
                ('d_o_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=200)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Christianity', 'Christianity'), ('Buddhism', 'Buddhism')], default='Islam', max_length=200)),
                ('nationality', models.CharField(max_length=100)),
                ('guardians_name', models.CharField(max_length=100)),
                ('guardians_con_no', models.IntegerField()),
                ('permanent_address', models.TextField()),
                ('present_address', models.TextField()),
                ('registration_no_of_ssc', models.IntegerField()),
                ('name_of_instituin_ssc', models.CharField(max_length=100)),
                ('roll_ssc', models.IntegerField()),
                ('group_ssc', models.CharField(choices=[('Science', 'Science'), ('ARS', 'ARS'), ('Business', 'Business')], default='Male', max_length=200)),
                ('year_ssc', models.CharField(choices=[('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003')], default='2016', max_length=200)),
                ('Board_ssc', models.CharField(choices=[('Sylhet', 'Sylhet'), ('Dhaka', 'Dhaka'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi')], default='Science', max_length=200)),
                ('gpa_ssc', models.FloatField()),
                ('registration_no_of_hsc', models.IntegerField()),
                ('name_of_instituin_hsc', models.CharField(max_length=100)),
                ('roll_hsc', models.IntegerField()),
                ('group_hsc', models.CharField(choices=[('Science', 'Science'), ('ARS', 'ARS'), ('Business', 'Business')], default='Male', max_length=200)),
                ('year_hsc', models.CharField(choices=[('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003')], default='2016', max_length=200)),
                ('Board_hsc', models.CharField(choices=[('Sylhet', 'Sylhet'), ('Dhaka', 'Dhaka'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi')], default='Science', max_length=200)),
                ('gpa_hsc', models.FloatField()),
                ('student_Img', models.ImageField(upload_to='studentimages/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myversity.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Done',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myversity.registration')),
            ],
        ),
    ]
