# Generated by Django 3.2.6 on 2022-03-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myversity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='referece_number',
            field=models.CharField(default='6731', max_length=7, unique=True),
        ),
    ]
