# Generated by Django 3.2.6 on 2022-03-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myversity', '0002_alter_registration_referece_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='referece_number',
            field=models.CharField(default='4318', max_length=7, unique=True),
        ),
    ]
