# Generated by Django 3.2.6 on 2022-05-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myversity', '0002_auto_20220506_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('allnmews', models.TextField()),
                ('news_phot', models.ImageField(upload_to='newsimages/')),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='referece_number',
            field=models.CharField(default='4519', max_length=7, unique=True),
        ),
    ]
