# Generated by Django 3.2.6 on 2022-05-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myversity', '0003_auto_20220522_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('alldes', models.TextField()),
                ('eventsimg', models.ImageField(upload_to='eventsimages/')),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='referece_number',
            field=models.CharField(default='1506', max_length=7, unique=True),
        ),
    ]
