# Generated by Django 3.2.6 on 2022-03-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myversity', '0003_auto_20220323_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='referece_number',
            field=models.CharField(default='2405', max_length=7, unique=True),
        ),
    ]
