# Generated by Django 4.0 on 2022-03-25 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myversity', '0004_alter_registration_referece_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='referece_number',
            field=models.CharField(default='9261', max_length=7, unique=True),
        ),
        migrations.CreateModel(
            name='Student_All_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departMent', models.CharField(choices=[('CSE', 'CSE'), ('ENGLISH', 'ENGLISH'), ('BBA', 'BBA'), ('BANGLA', 'BANGLA'), ('ISLAMIC STUDIES', 'ISLAMIC STUDIES'), ('EEE', 'EEE')], default='CSE', max_length=200)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('maritial_status', models.CharField(choices=[('Married', 'Married'), ('UnMarried', 'UnMarried')], default='Unmarried', max_length=200)),
                ('blood_Group', models.CharField(max_length=10)),
                ('national_id', models.IntegerField()),
                ('d_o_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=200)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Christianity', 'Christianity'), ('Buddhism', 'Buddhism')], default='Islam', max_length=200)),
                ('nationality', models.CharField(max_length=100)),
                ('guardians_name', models.CharField(max_length=100)),
                ('guardians_con_no', models.IntegerField()),
                ('permanent_address', models.TextField()),
                ('present_address', models.TextField()),
                ('registration_no_of_ssc', models.IntegerField()),
                ('name_of_instituin_ssc', models.CharField(max_length=100)),
                ('roll_ssc', models.IntegerField()),
                ('group_ssc', models.CharField(choices=[('Science', 'Science'), ('ARS', 'ARS'), ('Business', 'Business')], default='Male', max_length=200)),
                ('Board_ssc', models.CharField(choices=[('Science', 'Science'), ('ARS', 'ARS'), ('Business', 'Business')], default='Science', max_length=200)),
                ('gpa_ssc', models.FloatField()),
                ('registration_no_of_hsc', models.IntegerField()),
                ('name_of_instituin_hsc', models.CharField(max_length=100)),
                ('roll_hsc', models.IntegerField()),
                ('group_hsc', models.CharField(choices=[('Science', 'Science'), ('ARS', 'ARS'), ('Business', 'Business')], default='Male', max_length=200)),
                ('Board_hsc', models.CharField(choices=[('Science', 'Science'), ('ARS', 'ARS'), ('Business', 'Business')], default='Science', max_length=200)),
                ('gpa_hsc', models.FloatField()),
                ('student_Img', models.ImageField(upload_to='studentimages/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myversity.loginsite')),
            ],
        ),
    ]
