# Generated by Django 4.0 on 2022-03-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myversity', '0005_alter_registration_referece_number_student_all_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='referece_number',
            field=models.CharField(default='5362', max_length=7, unique=True),
        ),
    ]
