# Generated by Django 4.0 on 2022-03-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myversity', '0006_alter_registration_referece_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_all_info',
            name='year',
            field=models.CharField(choices=[('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003')], default='2016', max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='referece_number',
            field=models.CharField(default='1749', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='student_all_info',
            name='Board_hsc',
            field=models.CharField(choices=[('Sylhet', 'Sylhet'), ('Dhaka', 'Dhaka'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi')], default='Science', max_length=200),
        ),
        migrations.AlterField(
            model_name='student_all_info',
            name='Board_ssc',
            field=models.CharField(choices=[('Sylhet', 'Sylhet'), ('Dhaka', 'Dhaka'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi')], default='Science', max_length=200),
        ),
    ]
