# Generated by Django 3.2.6 on 2022-05-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myversity', '0007_auto_20220522_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='referece_number',
            field=models.CharField(default='7492', max_length=7, unique=True),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Deparetment',
        ),
    ]
