# Generated by Django 4.0 on 2022-03-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myversity', '0007_student_all_info_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_all_info',
            old_name='year',
            new_name='year_hsc',
        ),
        migrations.AddField(
            model_name='student_all_info',
            name='year_ssc',
            field=models.CharField(choices=[('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003')], default='2016', max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='referece_number',
            field=models.CharField(default='3586', max_length=7, unique=True),
        ),
    ]
