# Generated by Django 3.2.6 on 2022-05-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myversity', '0008_auto_20220522_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='referece_number',
            field=models.CharField(default='5168', max_length=7, unique=True),
        ),
    ]
