# Generated by Django 4.0.5 on 2022-08-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myversity', '0016_alter_registration_referece_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='referece_number',
            field=models.CharField(default='2509', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='student_all_info',
            name='group_hsc',
            field=models.CharField(choices=[('Science', 'Science'), ('Humanities', 'Humanities'), ('Business', 'Business')], default='Male', max_length=200),
        ),
        migrations.AlterField(
            model_name='student_all_info',
            name='group_ssc',
            field=models.CharField(choices=[('Science', 'Science'), ('Humanities', 'Humanities'), ('Business', 'Business')], default='Male', max_length=200),
        ),
    ]
