# Generated by Django 4.0.5 on 2022-08-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myversity', '0017_alter_registration_referece_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='referece_number',
            field=models.CharField(default='1950', max_length=7, unique=True),
        ),
    ]
