# Generated by Django 4.0.5 on 2022-06-12 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myversity', '0011_alter_registration_referece_number'),
        ('teacherapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherapp.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherapp.deparetment')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myversity.teacher')),
            ],
        ),
    ]
