# Generated by Django 4.0.5 on 2022-08-02 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myversity', '0017_alter_registration_referece_number_and_more'),
        ('teacherapp', '0007_alter_course_course_code_alter_course_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semisterregister',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myversity.loginsite'),
        ),
    ]
