# Generated by Django 4.0.5 on 2022-08-02 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myversity', '0018_alter_registration_referece_number'),
        ('teacherapp', '0008_alter_semisterregister_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semisterregister',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myversity.loginsite'),
        ),
    ]
